language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: bf8LZkpYANFuHwPBH/K8fgLHdwoMJnl3LxImaQBJcMGiAsLitLXoGxiW58TBmknafbgfQhU9c7+9Lm/sxGOIOk4xnnDbAC3EIU48zoFC29i0D/5UUkTKzKfVh0mFEcaJn090uY4ds5/f22uuMvhXjrNAqX5pnm5Rtn5pxBxMTZeo4mx4i7FvG7ZPQzsrTeWwrUcAt8K/ukDTkHJjJKXlqQr367tM3PYXXOfVdQz6VwWvBq/PWRkNhxCwz3yzvL8QXUGkLcMKN7kDJrCfUxnwOtWsPW7rIET1/GJRGgpYNYBQrISdIi0Hmw6+XnVHYOqehOeprOQL0a7Fy0hACaJAuXH8a3GJBnnHq9Edp2ZbhtjW1f7WSShKVYVHkRPnTYkZk8Ut/RdcB0cK1VHn79Xljsv5fhck/uN/AjqH/BAH5ExCMydd0XZQrnfre+e40oxLQDlLi7t1oD6ldHWyJUtIsNlQu+M96b4cA2XFAdfj6LDA1vyQ2VJ0mh3wZjrKw4j5xCWKAzwY7016rbapC4ohEHDeSZv4i1AU5ZR+uj6e2pR6fBpSTlv9YnFGSsKT6x7dBhw3SjzcUo2Mfu0l7xDOIElTgLW7aOKg3cz+FiEUgLKFj+gTpV/rWoxMdTRoaKH0cufjWd1zWUhGk0uKriKhFQO7HnRs/banBrtvo6MnFG4=
  on:
    branch: master
    repo: DEGJS/eventAggregator
